require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - app/javascript/**/*
    - bin/**/*
    - coverage/**/*
    - db/schema.rb
    - log/**/*
    - node_modules/**/*
    - public/**/*
    - spec/javascript/**/*
    - tmp/**/*
    - vendor/**/*
    - docker-volumes/**/*
  EnabledByDefault: true

### Rails

Rails/FilePath:
  EnforcedStyle: arguments

Rails/ApplicationController:
  Enabled: false

Rails/SchemaComment:
  Enabled: false

Rails/DefaultScope:
  Enabled: false

### Bundler

Bundler/OrderedGems:
  Enabled: false

Bundler/GemVersion:
  Enabled: false

### Metrics

Metrics/AbcSize:
  Max: 35

Metrics/MethodLength:
  Max: 50

Metrics/BlockLength:
  Max: 100

Metrics/ClassLength:
  Max: 150

Metrics/ParameterLists:
  Max: 6

### Layout

Layout:
  Enabled: false

Layout/LineLength:
  Max: 190
  AllowedPatterns: ['\A#'] # Allow long comments

### Style

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/MissingElse:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/InlineComment:
  Enabled: false

Style/StringHashKeys:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/IpAddresses:
  Enabled: false

Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/QuotedSymbols:
  EnforcedStyle: single_quotes

Style/FormatStringToken:
  Exclude:
    - config/routes.rb

Style/RequireOrder:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/Lambda:
  Enabled: false

# Lint

Lint/ConstantResolution:
  Enabled: false

# RSpec

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/AlignLeftLetBrace:
  Enabled: false

RSpec/AlignRightLetBrace:
  Enabled: false
